In [1]:
import os
import json
import git
import pandas as pd
import mysql.connector

In [3]:
#aggregated:

#aggre_insurance
path_1= "C:/Users/lenovo/Desktop/try/phonepe/pulse/data/aggregated/insurance/country/india/state/" 


agg_insur_list= os.listdir(path_1)

columns7= {"States":[], "Years":[], "Quarter":[], "Transaction_type":[], "Transaction_count":[],"Transaction_amount":[] }

for state in agg_insur_list:
    cur_states =path_1+state+"/"
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            A = json.load(data)

            for i in A["data"]["transactionData"]:
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns7["Transaction_type"].append(name)
                columns7["Transaction_count"].append(count)
                columns7["Transaction_amount"].append(amount)
                columns7["States"].append(state)
                columns7["Years"].append(year)
                columns7["Quarter"].append(int(file.strip(".json"))) 
                #we need only file as '1' not as '1.json', so we use .strip to cut '.json'. we need 1 as int only. 
                #this is done because 1,2,3,4,etc. of integer type json file names indicates quarterly response/timeperiod like 1st quarter, 2nd quarter, etc. this allows to identify and analyze data in easier way.


aggre_insurance = pd.DataFrame(columns7) #covert to dataframe

#making states into unique values:  converting all state names into a standardized format, it becomes easier to merge or compare data from different sources.
#selecting the states column from dataframe to access their features, str = to convert the state values to string
aggre_insurance["States"] = aggre_insurance["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar") 
aggre_insurance["States"] = aggre_insurance["States"].str.replace("-"," ")
aggre_insurance["States"] = aggre_insurance["States"].str.title() # to make all state names to title format like caps of first letter.
aggre_insurance['States'] = aggre_insurance['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")


#aggre_transaction
path_2 = "C:/Users/lenovo/Desktop/try/phonepe/pulse/data/aggregated/transaction/country/india/state/"   #this store only the path until state folder but not for each states.
agg_tran_list = os.listdir(path_2) #os.listdirecton- to change the path_1 as path since in above path acts as string. this also access inside "state" folder and gets all states.

# creating dictionary of lists like states, years, etc. to append all data from json file
columns1 ={"States":[], "Years":[], "Quarter":[], "Transaction_type":[], "Transaction_count":[],"Transaction_amount":[] }

#to access all states:
for state in agg_tran_list:
    cur_states =path_2+state+"/"  # this stores all the states path one by one in cur_states and it gets stores as string only
    agg_year_list = os.listdir(cur_states) #to change the cur_states as path since in above cur_states acts as string. this also access inside "each_state" folder and gets all years of each_state.

    for year in agg_year_list:
        cur_years = cur_states+year+"/"  # this stores all the years path one by one in cur_years and it gets stores as string only
        agg_file_list = os.listdir(cur_years)  #to change the cur_years as path since in above cur_years acts as string. this also access inside "each_year" folder and gets all json files of each_year.

        for file in agg_file_list:
            cur_files = cur_years+file # this stores all the years path one by one in cur_years and it gets stores as string only. since there no more path/folder is required so we stop using "/"
            data = open(cur_files,"r") # open and only read the files stored cur_files  using 'r'
            B = json.load(data)

            #since its dict form, we use i to access name, count, amount from "paymentInstruments"
            for i in B["data"]["transactionData"]:
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns1["Transaction_type"].append(name)  #append to the columns1 dict of lists
                columns1["Transaction_count"].append(count)
                columns1["Transaction_amount"].append(amount)
                columns1["States"].append(state)  # this is 'item' of above for loop so that it gets saved to respective list simultaneously.
                columns1["Years"].append(year)
                columns1["Quarter"].append(int(file.strip(".json"))) #we need only file as '1' not as '1.json', so we use .strip to cut '.json'. we need 1 as int only.

aggre_transaction = pd.DataFrame(columns1) #covert to dataframe

aggre_transaction["States"] = aggre_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_transaction["States"] = aggre_transaction["States"].str.replace("-"," ")
aggre_transaction["States"] = aggre_transaction["States"].str.title()
aggre_transaction['States'] = aggre_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")


#aggre_user
path_3 = "C:/Users/lenovo/Desktop/try/phonepe/pulse/data/aggregated/user/country/india/state/"
         
agg_user_list = os.listdir(path_3)

columns2 = {"States":[], "Years":[], "Quarter":[], "Brands":[],"Transaction_count":[], "Percentage":[]}

for state in agg_user_list:
    cur_states = path_3+state+"/"
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)
        
        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            C = json.load(data) #this C loads/prints data when we run in entire for loop and give print(C), if its run alone in separate cell then it shows only 'none' value for "usersByDevice"
            #print(C)


            #here it's used to avoid a NoneType error when accessing certain keys in the loaded JSON data. It allows the program to continue executing even if there are issues, by gracefully handling errors using the except block. 
            try:

                for i in C["data"]["usersByDevice"]: #we require only brand, count, percentage
                    brand = i["brand"]
                    count = i["count"]
                    percentage = i["percentage"]
                    columns2["Brands"].append(brand)
                    columns2["Transaction_count"].append(count)
                    columns2["Percentage"].append(percentage)
                    columns2["States"].append(state)
                    columns2["Years"].append(year)
                    columns2["Quarter"].append(int(file.strip(".json")))
            
            except:
                pass

aggre_user = pd.DataFrame(columns2) #covert to dataframe

aggre_user["States"] = aggre_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_user["States"] = aggre_user["States"].str.replace("-"," ")
aggre_user["States"] = aggre_user["States"].str.title()
aggre_user['States'] = aggre_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")


#map:

#map_insurance
path_4= "C:/Users/lenovo/Desktop/try/phonepe/pulse/data/map/insurance/hover/country/india/state/"

map_insur_list= os.listdir(path_4)

columns8= {"States":[], "Years":[], "Quarter":[], "Districts":[], "Transaction_count":[],"Transaction_amount":[] }

for state in map_insur_list:
    cur_states =path_4+state+"/"
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            D = json.load(data)

            for i in D["data"]["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns8["Districts"].append(name)
                columns8["Transaction_count"].append(count)
                columns8["Transaction_amount"].append(amount)
                columns8["States"].append(state)
                columns8["Years"].append(year)
                columns8["Quarter"].append(int(file.strip(".json")))


map_insurance = pd.DataFrame(columns8)

map_insurance["States"] = map_insurance["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_insurance["States"] = map_insurance["States"].str.replace("-"," ")
map_insurance["States"] = map_insurance["States"].str.title()
map_insurance['States'] = map_insurance['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

#map_transaction
path_5 = "C:/Users/lenovo/Desktop/try/phonepe/pulse/data/map/transaction/hover/country/india/state/"

map_tran_list = os.listdir(path_5 )

columns3 = {"States":[], "Years":[], "Quarter":[],"District":[], "Transaction_count":[],"Transaction_amount":[]}

for state in map_tran_list:
    cur_states = path_5+state+"/"
    map_year_list = os.listdir(cur_states)
    
    for year in map_year_list:
        cur_years = cur_states+year+"/"
        map_file_list = os.listdir(cur_years)
        
        for file in map_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            E = json.load(data)

            for i in E['data']["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns3["District"].append(name)
                columns3["Transaction_count"].append(count)
                columns3["Transaction_amount"].append(amount)
                columns3["States"].append(state)
                columns3["Years"].append(year)
                columns3["Quarter"].append(int(file.strip(".json")))

map_transaction = pd.DataFrame(columns3)

map_transaction["States"] = map_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_transaction["States"] = map_transaction["States"].str.replace("-"," ")
map_transaction["States"] = map_transaction["States"].str.title()
map_transaction['States'] = map_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

#map_user
path_6 = "C:/Users/lenovo/Desktop/try/phonepe/pulse/data/map/user/hover/country/india/state/"
map_user_list = os.listdir(path_6)

columns4 = {"States":[], "Years":[], "Quarter":[], "Districts":[], "RegisteredUser":[], "AppOpens":[]}

for state in map_user_list:
    cur_states = path_6+state+"/"
    map_year_list = os.listdir(cur_states)
    
    for year in map_year_list:
        cur_years = cur_states+year+"/"
        map_file_list = os.listdir(cur_years)
        
        for file in map_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            F = json.load(data)

            for i in F["data"]["hoverData"].items():
                district = i[0]
                registereduser = i[1]["registeredUsers"]
                appopens = i[1]["appOpens"]
                columns4["Districts"].append(district)
                columns4["RegisteredUser"].append(registereduser)
                columns4["AppOpens"].append(appopens)
                columns4["States"].append(state)
                columns4["Years"].append(year)
                columns4["Quarter"].append(int(file.strip(".json")))

map_user = pd.DataFrame(columns4)

map_user["States"] = map_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_user["States"] = map_user["States"].str.replace("-"," ")
map_user["States"] = map_user["States"].str.title()
map_user['States'] = map_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")


#top:

#top_insurance

path_7 = "C:/Users/lenovo/Desktop/try/phonepe/pulse/data/top/insurance/country/india/state/"


top_insur_list = os.listdir(path_7)

columns9 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_insur_list:
    cur_states = path_7+state+"/"
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)

        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            G = json.load(data)

            for i in G["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns9["Pincodes"].append(entityName)
                columns9["Transaction_count"].append(count)
                columns9["Transaction_amount"].append(amount)
                columns9["States"].append(state)
                columns9["Years"].append(year)
                columns9["Quarter"].append(int(file.strip(".json")))

top_insur = pd.DataFrame(columns9)

top_insur["States"] = top_insur["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_insur["States"] = top_insur["States"].str.replace("-"," ")
top_insur["States"] = top_insur["States"].str.title()
top_insur['States'] = top_insur['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")


#top_transaction
path_8 = "C:/Users/lenovo/Desktop/try/phonepe/pulse/data/top/transaction/country/india/state/"
top_tran_list = os.listdir(path_8)

columns5 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_tran_list:
    cur_states = path_8+state+"/"
    top_year_list = os.listdir(cur_states)
    
    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)
        
        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            H = json.load(data)

            for i in H["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns5["Pincodes"].append(entityName)
                columns5["Transaction_count"].append(count)
                columns5["Transaction_amount"].append(amount)
                columns5["States"].append(state)
                columns5["Years"].append(year)
                columns5["Quarter"].append(int(file.strip(".json")))

top_transaction = pd.DataFrame(columns5)

top_transaction["States"] = top_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_transaction["States"] = top_transaction["States"].str.replace("-"," ")
top_transaction["States"] = top_transaction["States"].str.title()
top_transaction['States'] = top_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")


#top_user
path_9 = "C:/Users/lenovo/Desktop/try/phonepe/pulse/data/top/user/country/india/state/"
top_user_list = os.listdir(path_9)

columns6 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "RegisteredUser":[]}

for state in top_user_list:
    cur_states = path_9+state+"/"
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)

        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            I = json.load(data)

            for i in I["data"]["pincodes"]:
                name = i["name"]
                registeredusers = i["registeredUsers"]
                columns6["Pincodes"].append(name)
                columns6["RegisteredUser"].append(registeredusers)
                columns6["States"].append(state)
                columns6["Years"].append(year)
                columns6["Quarter"].append(int(file.strip(".json")))

top_user = pd.DataFrame(columns6)

top_user["States"] = top_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_user["States"] = top_user["States"].str.replace("-"," ")
top_user["States"] = top_user["States"].str.title()
top_user['States'] = top_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [ ]:
# Table Creation
# mysql connection
mydb = mysql.connector.connect(
    host="localhost",          # MySQL server host
    user="root",               # MySQL username
    password="user2@2024",     # MySQL password
    database="phonepe_data",   # Name of the database you want to connect to
    port="3306",               # Port number (optional, default is 3306)
    auth_plugin='mysql_native_password'  # Authentication plugin (optional)
)

c = mydb.cursor()  # Initializing cursor object for executing queries


#aggregated insurance table
create_query1= '''CREATE TABLE if not exists aggregated_insurance (States varchar(50),
                                                                      Years int,
                                                                      Quarter int,
                                                                      Transaction_type varchar(50),
                                                                      Transaction_count bigint,
                                                                      Transaction_amount bigint
                                                                      )'''
c.execute(create_query1) #to execute create_query1 using cursor (c)
mydb.commit()

for index,row in aggre_insurance.iterrows():
    insert_query1 = '''INSERT INTO aggregated_insurance (States, Years, Quarter, Transaction_type, Transaction_count, Transaction_amount)
                                                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Transaction_type"],
              row["Transaction_count"],
              row["Transaction_amount"]
              )
    c.execute(insert_query1,values)
    mydb.commit()



#aggregated transaction table
create_query2 = '''CREATE TABLE if not exists aggregated_transaction (States varchar(50),
                                                                      Years int,
                                                                      Quarter int,
                                                                      Transaction_type varchar(50),
                                                                      Transaction_count bigint,
                                                                      Transaction_amount bigint
                                                                      )'''
c.execute(create_query2)
mydb.commit()

for index,row in aggre_transaction.iterrows():
    insert_query2 = '''INSERT INTO aggregated_transaction (States, Years, Quarter, Transaction_type, Transaction_count, Transaction_amount)
                                                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Transaction_type"],
              row["Transaction_count"],
              row["Transaction_amount"]
              )
    c.execute(insert_query2,values)
    mydb.commit()

#aggregated user table
create_query3 = '''CREATE TABLE if not exists aggregated_user (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                Brands varchar(50),
                                                                Transaction_count bigint,
                                                                Percentage float)'''
c.execute(create_query3)
mydb.commit()

for index,row in aggre_user.iterrows():
    insert_query3 = '''INSERT INTO aggregated_user (States, Years, Quarter, Brands, Transaction_count, Percentage)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Brands"],
              row["Transaction_count"],
              row["Percentage"])
    c.execute(insert_query3,values)
    mydb.commit()


#map
#map_insurance_table
create_query4 = '''CREATE TABLE if not exists map_insurance (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
c.execute(create_query4)
mydb.commit()

for index,row in map_insurance.iterrows():
    insert_query4 = '''INSERT INTO map_insurance (States, Years, Quarter, District, Transaction_count, Transaction_amount)
                                                    values (%s, %s, %s, %s, %s, %s)'''
    values = (
        row['States'],
        row['Years'],
        row['Quarter'],
        row['Districts'],
        row['Transaction_count'],
        row['Transaction_amount']
    )
    c.execute(insert_query4,values)
    mydb.commit() 

#map_transaction_table
create_query5 = '''CREATE TABLE if not exists map_transaction (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
c.execute(create_query5)
mydb.commit()

for index,row in map_transaction.iterrows():
        insert_query5 = '''
            INSERT INTO map_Transaction (States, Years, Quarter, District, Transaction_count, Transaction_amount)
            values (%s, %s, %s, %s, %s, %s)

        '''
        values = (
            row['States'],
            row['Years'],
            row['Quarter'],
            row['District'],
            row['Transaction_count'],
            row['Transaction_amount']
        )
        c.execute(insert_query5,values)
        mydb.commit() 


#map_user_table
create_query6 = '''CREATE TABLE if not exists map_user (States varchar(50),
                                                        Years int,
                                                        Quarter int,
                                                        Districts varchar(50),
                                                        RegisteredUser bigint,
                                                        AppOpens bigint)'''
c.execute(create_query6)
mydb.commit()

for index,row in map_user.iterrows():
    insert_query6 = '''INSERT INTO map_user (States, Years, Quarter, Districts, RegisteredUser, AppOpens)
                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Districts"],
              row["RegisteredUser"],
              row["AppOpens"])
    c.execute(insert_query6,values)
    mydb.commit()


#top:
#top_insurance_table
create_query7 = '''CREATE TABLE if not exists top_insurance (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                Pincodes int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)'''
c.execute(create_query7)
mydb.commit()

for index,row in top_insur.iterrows():
    insert_query7 = '''INSERT INTO top_insurance (States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["Transaction_count"],
              row["Transaction_amount"])
    c.execute(insert_query7,values)
    mydb.commit()

#top_transaction_table
create_query8 = '''CREATE TABLE if not exists top_transaction (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                pincodes int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)'''
c.execute(create_query8)
mydb.commit()

for index,row in top_transaction.iterrows():
    insert_query8 = '''INSERT INTO top_transaction (States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["Transaction_count"],
              row["Transaction_amount"])
    c.execute(insert_query8,values)
    mydb.commit()

#top_user_table
create_query9 = '''CREATE TABLE if not exists top_user (States varchar(50),
                                                        Years int,
                                                        Quarter int,
                                                        Pincodes int,
                                                        RegisteredUser bigint
                                                        )'''
c.execute(create_query9)
mydb.commit()

for index,row in top_user.iterrows():
    insert_query9 = '''INSERT INTO top_user (States, Years, Quarter, Pincodes, RegisteredUser)
                                            values(%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["RegisteredUser"])
    c.execute(insert_query9,values)
    mydb.commit()